spring:
  application:
    name: Bts

  datasource:
    url: jdbc:mysql://localhost:3306/btsdb
    username: root
    password: abc123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: sudeshjha2005@gmail.com
    password: wnuy phst tkfg koxy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}

server:
  port: 9090
  servlet:
    context-path: /api
file:
  upload:
    directory: uploads

api:
  url:
    path: http://localhost:9090/api

jwt:
  secret:
    key: 39558576A2627D621834747593E65263894955F7812763267B67274959


